---

version: '3.8'

services:
  app:
    image: node:14-slim
    working_dir: /var/local/app/
    volumes:
      - type: bind
        source: ${PWD}/
        target: /var/local/app/
    ports:
      - 8080:8080
