---

version: '3.8'

services:
  app:
    image: node:14-slim
    working_dir: /var/local/app/
    volumes:
      - type: bind
        source: ${PWD}/
        target: /var/local/app/
    ports:
      - 1234:1234
  nginx:
    image: nginx:stable
    volumes:
      - type: bind
        source: ${PWD}/
        target: /usr/share/nginx/html/
    ports:
      - 80:80
